apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: i6xg9kbh1-go
  janus-idp.io/tekton: i6xg9kbh1-go
  backstage.io/kubernetes-id: i6xg9kbh1-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: i6xg9kbh1-go
resources:
- deployment.yaml
- route.yaml
- service.yaml
